apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-app
  template:
    metadata:
      labels:
        app: opa-app
      name: opa
    spec:
      containers:
        - name: opa-app
          image: opa-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
        - name: opa
          image: openpolicyagent/opa:0.51.0
          ports:
            - name: http
              containerPort: 8181
          args:
            - "run"
            - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
            - "--server"
            - "/policies"
          volumeMounts:
            - readOnly: true
              mountPath: /policies
              name: example-policy
          livenessProbe:
            httpGet:
              scheme: HTTP              # assumes OPA listens on localhost:8181
              port: 8181
            initialDelaySeconds: 5      # tune these periods for your environment
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true  # Include bundle activation in readiness
              scheme: HTTP
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: example-policy
          configMap:
            name: example-policy
# without finding volume then k8s would not start the deployment