apiVersion: v1
kind: Service
metadata:
  name: opa-service
spec:
  type: LoadBalancer
  selector:
    app: opa-app
  ports:
    - protocol: "TCP"
      #      host port
      port: 8282
      #      cluster target port
      targetPort: 8181